import { Json } from '@/integrations/supabase/generated.types';

export type ProfileRow = {
  id: string;
  full_name: string | null;
  avatar_url: string | null;
  banner_url: string | null;
  bio: string | null;
  location: string | null;
  interests: string | null;
  occupation: string | null;
  height: string | null;
  weight: string | null;
  category: string | null;
  availability_status: string | null;
  languages: string[] | null;
  service_categories: string[] | null;
  price_range: Json | null;
  availability: string[] | null;
  gallery: string[] | null;
  age: number | null;
  gender: string | null;
  user_type: string;
  last_seen: string | null;
  reviews_count: number | null;
  is_verified: boolean | null;
  hair_color: string | null;
  hair_length: string | null;
  hair_type: string | null;
  eye_color: string | null;
  skin_tone: string | null;
  grooming: string | null;
  body_type: string | null;
  bust_size: string | null;
  dress_size: string | null;
  nickname: string | null;
  rating: number | null;
  reviews: number | null;
  audit_log: Json[];
  working_hours: Json;
  membership_level: 'basic' | 'premium' | 'vip' | 'bronze' | 'silver' | 'gold' | null;
  services: any[];
};