export type AvailabilityTranslationKeys =
  | "availability"
  | "startTime"
  | "endTime"
  | "selectStartTime"
  | "selectEndTime"
  | "addTimeSlot"
  | "selectDate"
  | "invalidTimeRange"
  | "timeSlotOverlap"
  | "timeSlotAdded"
  | "timeSlotRemoved"
  | "online"
  | "offline"
  | "busy";