export type DashboardTranslationKeys =
  | "welcome"
  | "lastLogin"
  | "dashboard"
  | "calendar"
  | "messages"
  | "settings"
  | "manageProfile"
  | "manageAppointments"
  | "manageMessages"
  | "manageSettings"
  | "editProfile"
  | "viewCalendar"
  | "viewMessages"
  | "editSettings"
  | "errorNavigating"
  | "errorLoadingFavorites"
  | "noFavorites";