export type NavigationTranslationKeys =
  | "home"
  | "about"
  | "services"
  | "contact"
  | "profile"
  | "search"
  | "searchProfiles"
  | "enterLocation"
  | "logout"
  | "logoutSuccess"
  | "logoutError"
  | "recentMessages"
  | "contacts"
  | "recentContacts" 
  | "favorites"
  | "yourFavorites";