export const languages = {
  de: {
    name: "Deutsch",
    code: "de",
    flag: "🇩🇪",
    translations: {
      welcome: "Willkommen",
      ageVerification: "Altersverifikation",
      ageQuestion: "Sind Sie über 18 Jahre alt?",
      yes: "Ja",
      no: "Nein",
      accessDenied: "Zugriff verweigert",
      home: "Startseite",
      about: "Über uns",
      services: "Dienstleistungen",
      contact: "Kontakt",
    },
  },
  en: {
    name: "English",
    code: "en",
    flag: "🇬🇧",
    translations: {
      welcome: "Welcome",
      ageVerification: "Age Verification",
      ageQuestion: "Are you over 18 years old?",
      yes: "Yes",
      no: "No",
      accessDenied: "Access Denied",
      home: "Home",
      about: "About",
      services: "Services",
      contact: "Contact",
    },
  },
  ru: {
    name: "Русский",
    code: "ru",
    flag: "🇷🇺",
    translations: {
      welcome: "Добро пожаловать",
      ageVerification: "Проверка возраста",
      ageQuestion: "Вам больше 18 лет?",
      yes: "Да",
      no: "Нет",
      accessDenied: "Доступ запрещен",
      home: "Главная",
      about: "О нас",
      services: "Услуги",
      contact: "Контакты",
    },
  },
  ro: {
    name: "Română",
    code: "ro",
    flag: "🇷🇴",
    translations: {
      welcome: "Bine ați venit",
      ageVerification: "Verificarea vârstei",
      ageQuestion: "Aveți peste 18 ani?",
      yes: "Da",
      no: "Nu",
      accessDenied: "Acces interzis",
      home: "Acasă",
      about: "Despre noi",
      services: "Servicii",
      contact: "Contact",
    },
  },
  it: {
    name: "Italiano",
    code: "it",
    flag: "🇮🇹",
    translations: {
      welcome: "Benvenuto",
      ageVerification: "Verifica dell'età",
      ageQuestion: "Hai più di 18 anni?",
      yes: "Sì",
      no: "No",
      accessDenied: "Accesso negato",
      home: "Home",
      about: "Chi siamo",
      services: "Servizi",
      contact: "Contatti",
    },
  },
  es: {
    name: "Español",
    code: "es",
    flag: "🇪🇸",
    translations: {
      welcome: "Bienvenido",
      ageVerification: "Verificación de edad",
      ageQuestion: "¿Tienes más de 18 años?",
      yes: "Sí",
      no: "No",
      accessDenied: "Acceso denegado",
      home: "Inicio",
      about: "Sobre nosotros",
      services: "Servicios",
      contact: "Contacto",
    },
  },
  fr: {
    name: "Français",
    code: "fr",
    flag: "🇫🇷",
    translations: {
      welcome: "Bienvenue",
      ageVerification: "Vérification de l'âge",
      ageQuestion: "Avez-vous plus de 18 ans?",
      yes: "Oui",
      no: "Non",
      accessDenied: "Accès refusé",
      home: "Accueil",
      about: "À propos",
      services: "Services",
      contact: "Contact",
    },
  },
};

export type Language = keyof typeof languages;
export type TranslationKey = keyof typeof languages.de.translations;