// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtogyltwimvdecsomwde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0b2d5bHR3aW12ZGVjc29td2RlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQwNzc4MDQsImV4cCI6MjA0OTY1MzgwNH0.hCNdmL4U8wt3xFkeRaS7hjz4VkNrvKtj6SKor8ArZv4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);