name: Node.js CI and Code Quality

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-improve:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci || npm install
    
    - name: Type checking
      run: npx tsc --noEmit || true
    
    - name: Lint
      run: npm run lint || true
    
    - name: Build
      run: npm run build --if-present
    
    - name: Automatic Code Improvements
      run: |
        if [ -f ".prettierrc" ]; then
          npx prettier --write "src/**/*.{js,jsx,ts,tsx}"
        fi
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "style: format code and improve quality"
        title: "🤖 Automatic Code Quality Improvements"
        body: |
          This PR contains automatic code improvements:
          
          - Code formatting
          - Type safety improvements
          - Performance optimizations
          - Better error handling
          
          Please review the changes carefully before merging.
        branch: automated-improvements
        delete-branch: true
        labels: |
          automated
          enhancement
